language: haskell

ghc:
  - 7.0.4
  - 7.4.2
  - 7.6.3
  - 7.8.4

install:
  - cabal update
  - cabal install netlist/ verilog/ -j --only-dependencies

script:
  - ( cd netlist/ ; cabal configure ; cabal install )
  - ( cd verilog/ ; cabal configure ; cabal install )
  - ( cd netlist-to-vhdl; cabal install -j --only-dependencies; cabal configure ; cabal install )
  - ( cd netlist-to-verilog; cabal install -j --only-dependencies; cabal configure ; cabal install )

